export enum SecurityEventType {
  UNKNOWN_SENSOR = 'UNKNOWN_SENSOR',
  INACTIVE_SENSOR_ACTIVITY = 'INACTIVE_SENSOR_ACTIVITY',
  ANOMALOUS_SENSOR_VALUE = 'ANOMALOUS_SENSOR_VALUE',
  FAILED_LOGIN = 'FAILED_LOGIN',
}